services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crud_docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: 1234

  backend:
    build: ./crudBackend
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8080"

  frontend:
    build: ./crudFrontend
    restart: unless-stopped
    ports:
      - "5173:8080"

volumes:
  mysql_data:
